baseurl = "/"
title = "Faishal Irawan"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

disqusShortname = "mfaishal"

[params]
  
  subtitle = "mfaishal.com"
  homeSubtitle = "I make website"
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = true

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/faishalirwn"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/faishalirwn"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/faishalirwn"
  [[params.social]]
    name = "github"
    url = "https://github.com/faishalirwn"
  [[params.social]]
    name = "email"
    url = "mailto:muhammadfaishal193@gmail.com"

[languages]
  [languages.en]
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"

    [languages.en.params.logo]
      logoText = "mfaishal.com"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
          identifier = "showcase"
          name = "Showcase"
          url = "/showcase"
          weight = 1
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 3